spring:
  application:
    name: luizalabs-orders-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders_db}
    username: ${DB_USER:usr_orders_db}
    password: ${DB_PASS:pw_orders_db}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${DESAFIO_LABS_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: ${DESAFIO_LABS_RUN_FLYWAY:true}
    check-location: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  shutdown: ${SERVER_SHUTDOWN_MODE:graceful}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

api:
  info:
    title: ${API_TITLE:LuizaLabs - API de Gest√£o de Pedidos}
    version: ${API_VERSION:1.0.0}
    description: ${API_DESCRIPTION:API REST para processamento de arquivos de pedidos desnormalizados}
  contact:
    name: ${API_CONTACT_NAME:Lucas Peres}
    email: ${API_CONTACT_EMAIL:lucasperes.lpc@gmail.com}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.luizalabs.orders: ${ORDER_LOG_LEVEL:DEBUG}
